### ISSUE TITLE
Feature: new command sudo-retry

### ISSUE THREAD

**Issue by razzius** [razzius/fish-functions#11]
Retries the last failed command, with sudo

**Comment by razzius** [comment]
Now that `!!` is possible with abbrs, should do that instead

**Comment by razzius** [comment]
Tbh this is an anti-pattern; running a sudo command without inspecting it is a recipe for problems

Maybe what I want is a keyboard shortcut to prepend sudo onto a line. But I don't much use this, many sudo-necessary commands have abbrs that insert the `sudo`

**Comment by ccoVeille** [comment]
Hi,

I'm following your repository for a while. And I can say I appreciate it a lot. Thanks for publicly sharing your fish config and functions.

I agree with you about the dangerous consequence of something that would implement the sudo-retry idea.

I'm also using abbr to complete all the commands that requires sudo.

I assume you have something like this:

```shell
abbr -a -- apt-get 'sudo apt-get'
abbr -a -- apt 'sudo apt'
abbr -a -- service 'sudo service'
# (…)
```

Anyway, if anyone is interested by something that implements what is described in the issue, I would recommend using https://github.com/nvbn/thefuck

There is also this fish plugin to map it with keyboard shortcut
https://github.com/oh-my-fish/plugin-thefuck

**Comment by ccoVeille** [comment]
Just found back this function

https://github.com/oh-my-fish/plugin-sudope

It doesn't run anything, it just rewrites the command without running it. So you have to press enter
