### ISSUE TITLE
git-commit: command not found

### ISSUE THREAD

**Issue by sl5net** [razzius/fish-functions#21]
```sh
git-commit update version nr
git-commit: command not found
startswith: command not found
~/.config/fish/config.fish (line 177): 
    if not contains $exit_status 0 $cancel_status && not startswith retry "$argv" && not startswith sudo-retry "$argv"
```

becouse when i deleted the
 ~/.config/fish/config.fish
it was resoured quck with a empty
~/.config/fish/config.fish

therefore i copied manually your content in the (nearly) empty  ~/.config/fish/config.fish

then i pasted the content of my old/backup inside of ~/.config/fish/config.fish (at the top).

jumped in a repo directory did a little change and tried your commit: 

tried the `git-commit update version nr` as you see above.

**Comment by razzius** [comment]
The `git-commit` script comes from the https://github.com/razzius/fish-functions/tree/main/functions directory - only copying the config.fish isn't enough to use the functions. Clone the entire repository to get all the functions.

Even the config.fish alone depends on these functions, which is why you're getting further errors.

**Comment by razzius** [comment]
I have moved the fish config out to https://sr.ht/~razzi/dotfiles/ so it should be clearer now how this repository is intended to be used.

**Comment by ccoVeille** [comment]
> I have moved the fish config out to https://sr.ht/~razzi/dotfiles/ so it should be clearer now how this repository is intended to be used.

The link is broken. Could you fix it?

**Comment by razzius** [comment]
Hey yeah sorry this url works: https://git.sr.ht/~razzi/.dotfiles
